version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - ${PORT}:80
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: America/Chicago

      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'false' #default true
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'true' #default false
      RECIPE_DISABLE_AMOUNT: 'false'
      AUTO_BACKUP_ENABLED: 'true'

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - mealie:/app/data

volumes:
  mealie:
