version: "2.1"
services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: Piwigo
    environment:
      - PUID=${MYPUID}
      - PGID=${MYPGID}
      - TZ=Europe/Bucharest
    volumes:
      - /home/andrew/docker/piwigo/config:/config
      - photos:/gallery
    ports:
      - ${PIWIGOPORT}:80
    restart: always
  db:
    image: mysql
    container_name: Piwigo-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPWD}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPWD}
    volumes:
      - /home/andrew/docker/piwigo/db:/var/lib/mysql
      
volumes:
  photos:
    external: true
    name: photos  #Name of existing volume
