---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer-${NAME}
    volumes:
      # Make sure this folder is writeable by the user below before deploying the container
      - /home/docker/homer/${NAME}:/www/assets
    ports:
      - ${PORT}:8080
    user: ${ID1}:${ID2} # default 1000:1000
    environment:
      - INIT_ASSETS=1 # default 1
#volumes:
#  homer:
