---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer-${NAME}
    volumes:
      # - /home/docker/homer-${NAME}:/www/assets
      - ${VOLUME}:/www/assets
    ports:
      - ${PORT}:8080
    user: 911:911 # default 1000:1000
    environment:
      - INIT_ASSETS=1 # default 1
volumes:
  ${VOLUME}:
