---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer-${NAME}
    volumes:
      - homer:/www/assets
    ports:
      - ${PORT}:8080
    user: 1000:1000 # default 1000:1000
    environment:
      - INIT_ASSETS=1 # default 1
volumes:
  homer:
